name: homeweb_deploy   # 워크플로우 이름

on:                          # 언제 실행할지
  push:                      # push가 발생하면 실행
    branches: ["master"]       # 단, main 브랜치에 push 된 경우만

jobs:
  build:
    runs-on: ubuntu-latest   # GitHub이 빌드를 돌릴 가상머신 환경

    steps:                   # 단계별 실행
      - name: Checkout repository
        uses: actions/checkout@v3   # 내 repo 코드를 불러오기

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # 도커 빌드 환경 준비

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}   # GitHub Secrets에서 가져오기
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: chan2slo/homeweb_test:latest   # 이 이름으로 Docker Hub에 업로드 #test